services:
  postgres:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-prod
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-prod
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    depends_on:
      - backend

volumes:
  pgdata:
